
import type { Metadata } from 'next'
import '../fonts/sf.css'
import './globals.css'
import Logo from '@/components/Logo'
import Menu from '@/components/Menu'
import { headers } from 'next/headers';
import detectMobile from '@/helpers/detectedPhone'
import Footer from '@/components/Footer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="ru">
      {/* <body className="flex min-h-screen flex-col relative bg-black"> */}
      <body className="flex min-h-screen flex-col relative bg-black">
        {/* <div className='text-white'>{JSON.stringify(detectMobile(headers().get('user-agent') || ""))}</div> */}
        <div id="gradient1" className="fixed top-0 left-0 right-0 bottom-0">
          <div className="bg-gradient-radial from-[#e100ff73] from-0% to-[#0000] to-70% z-[-1] absolute left-[-300px] top-[-200px] w-[600px] h-[600px]" />
          <div className="bg-gradient-radial from-[#8349ff73] from-0% to-[#0000] to-70% z-[-1] absolute left-[-100px] top-[-400px] w-[900px] h-[700px]" />
          <div className="bg-gradient-radial from-[#0011ff73] from-0% to-[#0000] to-70% z-[-1] absolute left-[300px] top-[-450px] w-[900px] h-[700px]" />
        </div>
        <div id="gradient2" className="fixed top-0 left-0 right-0 bottom-0">
          <div className="bg-gradient-radial from-[#e100ff73] from-0% to-[#0000] to-70% z-[-1] absolute left-[-300px] top-[-200px] w-[600px] h-[600px]" />
          <div className="bg-gradient-radial from-[#8349ff73] from-0% to-[#0000] to-70% z-[-1] absolute left-[-100px] top-[-400px] w-[900px] h-[700px]" />
          <div className="bg-gradient-radial from-[#0011ff73] from-0% to-[#0000] to-70% z-[-1] absolute left-[300px] top-[-450px] w-[900px] h-[700px]" />
        </div>
        {/* <div className="ml-4 mr-4"> */}
        {/* 
          <header className="flex justify-between w-full items-center pt-[20px]">
            <Logo />
            <Menu />
          </header>
           */}
        {/* <div className=' overflow-auto  h-full'> */}
          {children}
        {/* </div> */}
        {/* <Footer /> */}
        {/* </div> */}
      </body>
    </html>
  )
}
